package Procesos;

import ManejoArchivos.Archivos;
import ManejoArchivos.ProcesoNomina;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class ReversarNomina extends javax.swing.JFrame {

    /**
     * Creates new form GenerarNomina
     */
    public ReversarNomina() {
        initComponents();
    }
    public int Año;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Establecerbt = new javax.swing.JButton();
        txtdia = new javax.swing.JTextField();
        txtyear = new com.toedter.calendar.JYearChooser();
        mesesCB = new javax.swing.JComboBox<>();
        salirbt = new javax.swing.JButton();
        generarbt = new javax.swing.JButton();
        jlabelId_nomina = new javax.swing.JLabel();
        jTextID_nomina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reversar Nómina");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(168, 205, 159));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Fecha de Nómina:");

        Establecerbt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Establecerbt.setText("Establecer");
        Establecerbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstablecerbtActionPerformed(evt);
            }
        });

        txtdia.setEditable(false);
        txtdia.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtdia.setText("30");

        mesesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        salirbt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        salirbt.setText("Salir");
        salirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbtActionPerformed(evt);
            }
        });

        generarbt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        generarbt.setText("Reversar");
        generarbt.setEnabled(false);
        generarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarbtActionPerformed(evt);
            }
        });

        jlabelId_nomina.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jlabelId_nomina.setText("ID de Nomina");

        jTextID_nomina.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(generarbt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salirbt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mesesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtyear, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(Establecerbt)))
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelId_nomina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextID_nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {generarbt, salirbt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelId_nomina)
                    .addComponent(jTextID_nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Establecerbt, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarbt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirbt))
                .addGap(26, 26, 26))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {generarbt, salirbt});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EstablecerbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstablecerbtActionPerformed
        if(mesesCB.getSelectedItem().equals("Febrero")){
            txtdia.setText("28");
        }else{
            txtdia.setText("30");
        }
        ProcesoNomina ProcN = new ProcesoNomina();

        Año= txtyear.getYear();

            if (ProcN.BuscarFechaNómina((mesesCB.getSelectedIndex()+1), Año)) {
                jTextID_nomina.setText(ProcN.BuscarIDNómina((mesesCB.getSelectedIndex()+1), Año));
                generarbt.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error, no se encontró ninguna nómina con la fecha ingresada");
                jTextID_nomina.setText("");
                generarbt.setEnabled(false);
            }

        
    }//GEN-LAST:event_EstablecerbtActionPerformed

    private void salirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbtActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirbtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        File f = new File("D:\\DB\\Nominas.txt");

        if (!f.exists()) {
            JOptionPane.showMessageDialog(rootPane, "No existe ningún nómina para reversar", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }        
    }//GEN-LAST:event_formWindowOpened

    private void generarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarbtActionPerformed
      ModificarNómina();

        File archPDF = new File("D:\\PDF\\Nomina - " + mesesCB.getSelectedItem() + " " + Año + ".pdf");
        if (archPDF.exists()) {
            archPDF.delete();
        }

        JOptionPane.showMessageDialog(rootPane, "La nómina se ha reversado correctamente");
        jTextID_nomina.setText("");

        generarbt.setEnabled(false);
        
    }//GEN-LAST:event_generarbtActionPerformed
   public void ModificarNómina() {
        File Nomina = new File("D:\\DB\\Nominas.txt");
        File Aux = new File("D:\\DB\\NominasAux.txt");

        try {
            if (!Aux.exists()) {
                Aux.createNewFile();
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        Scanner s;
        Archivos AR = new Archivos();

        try {
            if (Nomina.exists()) {
                s = new Scanner(Nomina);

                while (s.hasNextLine()) {
                    String linea = s.nextLine();
                    Scanner s1 = new Scanner(linea);
                    s1.useDelimiter("\\s*;\\s*");

                    ArrayList<String> DatosNómina = new ArrayList<>();

                    while (s1.hasNext()) {
                        DatosNómina.add(s1.next());
                    }

                    if (DatosNómina.get(0).equals(jTextID_nomina.getText())) {
                        ActualizarCoop(DatosNómina);
                    } else {
                        AR.Guardar(linea, Aux);
                    }

                }

                s.close();

                AR.BorrarArchivo(Nomina);
                Aux.renameTo(Nomina);

            } else {
                JOptionPane.showMessageDialog(rootPane, "El archivo de Nómina no existe");
            }
        } catch (IOException e) {
            System.out.println(e);
        }

    }

    public void ActualizarCoop(ArrayList<String> DatosNómina) {
        ProcesoNomina ProcN = new ProcesoNomina();
        Archivos AR = new Archivos();
        ArrayList<String> DatosCoop = ProcN.BuscarDatosCoop(DatosNómina.get(1));

        if (DatosCoop != null) {
            String LineaAntigua = DatosCoop.get(0) + ";" + DatosCoop.get(1) + ";" + DatosCoop.get(2);
            double Balance_Acum = Double.parseDouble(DatosCoop.get(2));
            double Valor_Coop = Double.parseDouble(DatosNómina.get(7));
            Balance_Acum -= Valor_Coop;
            String LineaActual = DatosCoop.get(0) + ";" + DatosCoop.get(1) + ";" + Balance_Acum;

            try {

                File Coop = new File("D:\\DB\\Cooperativa.txt");
                if (!Coop.exists()) {
                    Coop.createNewFile();
                    System.out.println("Error, El archivo de Cooperativas no existe");
                } else {
                    AR.ModificarArchivo(LineaAntigua, LineaActual, Coop);
                }

            } catch (IOException e) {
                System.out.println(e);
            }

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReversarNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReversarNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReversarNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReversarNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReversarNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Establecerbt;
    private javax.swing.JButton generarbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextID_nomina;
    private javax.swing.JLabel jlabelId_nomina;
    private javax.swing.JComboBox<String> mesesCB;
    private javax.swing.JButton salirbt;
    private javax.swing.JTextField txtdia;
    private com.toedter.calendar.JYearChooser txtyear;
    // End of variables declaration//GEN-END:variables
}
