package Consultas;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asistente
 */
public class ConsultaEmpPuesto extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaEmpPuesto
     */
    public ConsultaEmpPuesto() {
        initComponents();
        Tabla = (DefaultTableModel) tablempp.getModel();
    }
    public DefaultTableModel Tabla;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablempp = new javax.swing.JTable();
        consultarbt = new javax.swing.JButton();
        salirbt = new javax.swing.JButton();
        jtitulo = new javax.swing.JLabel();
        jLabel_ID_Puesto = new javax.swing.JLabel();
        txtIDdpt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Empleados por Puesto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tablempp.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tablempp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Dirección", "Teléfono", "Sexo", "ID Departamento", "Fecha de Ingreso", "ID Puesto", "Cooperativa", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablempp.getTableHeader().setResizingAllowed(false);
        tablempp.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablempp);
        if (tablempp.getColumnModel().getColumnCount() > 0) {
            tablempp.getColumnModel().getColumn(0).setMinWidth(80);
            tablempp.getColumnModel().getColumn(0).setPreferredWidth(80);
            tablempp.getColumnModel().getColumn(0).setMaxWidth(80);
            tablempp.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablempp.getColumnModel().getColumn(3).setPreferredWidth(100);
            tablempp.getColumnModel().getColumn(6).setMinWidth(45);
            tablempp.getColumnModel().getColumn(6).setPreferredWidth(45);
            tablempp.getColumnModel().getColumn(6).setMaxWidth(45);
            tablempp.getColumnModel().getColumn(7).setPreferredWidth(100);
            tablempp.getColumnModel().getColumn(8).setPreferredWidth(100);
            tablempp.getColumnModel().getColumn(11).setMinWidth(110);
            tablempp.getColumnModel().getColumn(11).setPreferredWidth(110);
            tablempp.getColumnModel().getColumn(11).setMaxWidth(110);
        }

        consultarbt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        consultarbt.setText("Consultar");
        consultarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarbtActionPerformed(evt);
            }
        });

        salirbt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        salirbt.setText("Salir");
        salirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbtActionPerformed(evt);
            }
        });

        jtitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jtitulo.setText("Consulta de Empleados por Puesto");

        jLabel_ID_Puesto.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_ID_Puesto.setText("ID_Puesto");

        txtIDdpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDdptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ID_Puesto)
                .addGap(18, 18, 18)
                .addComponent(txtIDdpt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consultarbt)
                .addGap(18, 18, 18)
                .addComponent(salirbt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtitulo)
                .addGap(348, 348, 348))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarbt)
                    .addComponent(salirbt)
                    .addComponent(jLabel_ID_Puesto)
                    .addComponent(txtIDdpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbtActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirbtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void consultarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarbtActionPerformed
        String buscar, id, nombre, appat, apmat, direc, telefono, sexo, iddpt, fechain, idp, coop, salario;
        Tabla.getDataVector().removeAllElements();
        Tabla.fireTableDataChanged();
        
        buscar=txtIDdpt.getText();
        File f = new File("D:\\DB\\Empleados.txt");
        
        try{
            if(!f.exists()){
                JOptionPane.showMessageDialog(null, "ESTE ARCHIVO NO EXISTE");
            }
            else{
                Scanner a = new Scanner(f);
                while(a.hasNextLine()){
                    String ln = a.nextLine();
                    Scanner a1 = new Scanner(ln);
                    
                    a1.useDelimiter("\\s*;\\s*");
                    
                    id=a1.next();
                    nombre=a1.next();
                    appat=a1.next();
                    apmat=a1.next();
                    direc=a1.next();
                    telefono=a1.next();
                    sexo=a1.next();
                    iddpt=a1.next();
                    fechain=a1.next();
                    idp=a1.next();
                    coop=a1.next();
                    salario=a1.next();
                    
                    if(fechain.contains(buscar)){
                        Tabla.addRow(new Object[]{id, nombre, appat, apmat, direc, telefono, sexo, iddpt, fechain, idp, coop, "$"+salario});
                    }
                }
                a.close();
            }
        }
        catch(IOException e){
            
        }
    }//GEN-LAST:event_consultarbtActionPerformed

    private void txtIDdptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDdptActionPerformed
        consultarbtActionPerformed(evt);
    }//GEN-LAST:event_txtIDdptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaEmpPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaEmpPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaEmpPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaEmpPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaEmpPuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarbt;
    private javax.swing.JLabel jLabel_ID_Puesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jtitulo;
    private javax.swing.JButton salirbt;
    private javax.swing.JTable tablempp;
    private javax.swing.JTextField txtIDdpt;
    // End of variables declaration//GEN-END:variables
}
