package Desplegables;

public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etqEstado = new javax.swing.JLabel();
        idlbl = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        nombrelbl = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellidopat = new javax.swing.JTextField();
        apellidomatlbl = new javax.swing.JLabel();
        txtapellidomat = new javax.swing.JTextField();
        apellidopatlbl = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        hombrebt = new javax.swing.JRadioButton();
        mujerbt = new javax.swing.JRadioButton();
        direccionlbl = new javax.swing.JLabel();
        telefonolbl = new javax.swing.JLabel();
        sexolbl = new javax.swing.JLabel();
        txtiddepart = new javax.swing.JTextField();
        iddepartlbl = new javax.swing.JLabel();
        fechalbl = new javax.swing.JLabel();
        txtfechaingreso = new com.toedter.calendar.JDateChooser();
        txtidpuesto = new javax.swing.JTextField();
        idpuestolbl = new javax.swing.JLabel();
        sibt = new javax.swing.JRadioButton();
        nobt = new javax.swing.JRadioButton();
        cooperativalbl = new javax.swing.JLabel();
        txtsalario = new javax.swing.JTextField();
        salariolbl = new javax.swing.JLabel();
        guardarbt = new javax.swing.JButton();
        limpiarbt = new javax.swing.JButton();
        salirbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados");
        setResizable(false);

        etqEstado.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        etqEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        idlbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        idlbl.setText("ID");

        txtid.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        nombrelbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        nombrelbl.setText("Nombre");

        txtnombre.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        txtapellidopat.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        apellidomatlbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        apellidomatlbl.setText("Apellido Materno");

        txtapellidomat.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        apellidopatlbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        apellidopatlbl.setText("Apellido Paterno");

        txtdireccion.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        txttelefono.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        buttonGroup1.add(hombrebt);
        hombrebt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        hombrebt.setText("Hombre");

        buttonGroup1.add(mujerbt);
        mujerbt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        mujerbt.setText("Mujer");

        direccionlbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        direccionlbl.setText("Dirección");

        telefonolbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        telefonolbl.setText("Teléfono");

        sexolbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        sexolbl.setText("Sexo");

        txtiddepart.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        iddepartlbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        iddepartlbl.setText("ID Departamento");

        fechalbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        fechalbl.setText("Fecha de Ingreso");

        txtfechaingreso.setDateFormatString("d-MM-y");
        txtfechaingreso.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        txtidpuesto.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        idpuestolbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        idpuestolbl.setText("ID Puesto");

        buttonGroup2.add(sibt);
        sibt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        sibt.setText("Si");

        buttonGroup2.add(nobt);
        nobt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        nobt.setText("No");

        cooperativalbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cooperativalbl.setText("Cooperativa");

        txtsalario.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        salariolbl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        salariolbl.setText("Salario");

        guardarbt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        guardarbt.setText("Guardar");

        limpiarbt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        limpiarbt.setText("Limpiar");
        limpiarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtActionPerformed(evt);
            }
        });

        salirbt.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        salirbt.setText("Salir");
        salirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etqEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idlbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nombrelbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(direccionlbl)
                                            .addComponent(telefonolbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtdireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                            .addComponent(txttelefono)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(apellidomatlbl)
                                            .addComponent(apellidopatlbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtapellidopat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtapellidomat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(sexolbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(hombrebt)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mujerbt))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(iddepartlbl)
                                                .addComponent(fechalbl))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtfechaingreso, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(txtiddepart)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(idpuestolbl)
                                                .addComponent(cooperativalbl))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtidpuesto)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(sibt)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(nobt)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(salariolbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(guardarbt)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(limpiarbt)
                                                .addGap(32, 32, 32)))
                                        .addGap(9, 9, 9)
                                        .addComponent(salirbt)))))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellidopat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidopatlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellidomat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidomatlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonolbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hombrebt)
                    .addComponent(mujerbt)
                    .addComponent(sexolbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtiddepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iddepartlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechalbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idpuestolbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sibt)
                    .addComponent(nobt)
                    .addComponent(cooperativalbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salariolbl))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarbt)
                    .addComponent(limpiarbt)
                    .addComponent(salirbt))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbtActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirbtActionPerformed

    private void limpiarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtActionPerformed
        etqEstado.setText("");
        txtid.setText("");
        txtnombre.setText("");
        txtapellidopat.setText("");
        txtapellidomat.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        if(hombrebt.isSelected()){
            hombrebt.setSelected(false);
        }else if(mujerbt.isSelected()){
            mujerbt.setSelected(false);
        }
        txtiddepart.setText("");
        txtfechaingreso.setDate(null);
        txtidpuesto.setText("");
        if(sibt.isSelected()){
            sibt.setSelected(false);
        }else if(nobt.isSelected()){
            nobt.setSelected(false);
        }
        txtsalario.setText("");
    }//GEN-LAST:event_limpiarbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidomatlbl;
    private javax.swing.JLabel apellidopatlbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cooperativalbl;
    private javax.swing.JLabel direccionlbl;
    private javax.swing.JLabel etqEstado;
    private javax.swing.JLabel fechalbl;
    private javax.swing.JButton guardarbt;
    private javax.swing.JRadioButton hombrebt;
    private javax.swing.JLabel iddepartlbl;
    private javax.swing.JLabel idlbl;
    private javax.swing.JLabel idpuestolbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiarbt;
    private javax.swing.JRadioButton mujerbt;
    private javax.swing.JRadioButton nobt;
    private javax.swing.JLabel nombrelbl;
    private javax.swing.JLabel salariolbl;
    private javax.swing.JButton salirbt;
    private javax.swing.JLabel sexolbl;
    private javax.swing.JRadioButton sibt;
    private javax.swing.JLabel telefonolbl;
    private javax.swing.JTextField txtapellidomat;
    private javax.swing.JTextField txtapellidopat;
    private javax.swing.JTextField txtdireccion;
    private com.toedter.calendar.JDateChooser txtfechaingreso;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtiddepart;
    private javax.swing.JTextField txtidpuesto;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
