package Desplegables;

import Consultas.ConsultaDepart;
import Consultas.ConsultaEmp;
import Consultas.ConsultaPuestos;
import Login.LoginUsuario;

/**
 *
 * @author LIKELIAS
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLetrero = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menMantenimientos = new javax.swing.JMenu();
        itmUsuario = new javax.swing.JMenuItem();
        itmDepart = new javax.swing.JMenuItem();
        itmPuesto = new javax.swing.JMenuItem();
        itmEmpleado = new javax.swing.JMenuItem();
        menProcesos = new javax.swing.JMenu();
        generarnomina = new javax.swing.JMenuItem();
        reversarnomina = new javax.swing.JMenuItem();
        consulta = new javax.swing.JMenu();
        Departamentos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Empleados = new javax.swing.JMenuItem();
        EmpDepart = new javax.swing.JMenuItem();
        EmpPuestos = new javax.swing.JMenuItem();
        EmpFecha = new javax.swing.JMenuItem();
        NominaFecha = new javax.swing.JMenuItem();
        NominaIDEmp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de Inicio");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblLetrero.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(lblLetrero, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblLetrero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        menMantenimientos.setText("Mantenimientos");

        itmUsuario.setText("Usuarios");
        itmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmUsuarioActionPerformed(evt);
            }
        });
        menMantenimientos.add(itmUsuario);

        itmDepart.setText("Departamentos");
        itmDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDepartActionPerformed(evt);
            }
        });
        menMantenimientos.add(itmDepart);

        itmPuesto.setText("Puestos");
        itmPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPuestoActionPerformed(evt);
            }
        });
        menMantenimientos.add(itmPuesto);

        itmEmpleado.setText("Empleados");
        itmEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEmpleadoActionPerformed(evt);
            }
        });
        menMantenimientos.add(itmEmpleado);

        jMenuBar1.add(menMantenimientos);

        menProcesos.setText("Procesos");

        generarnomina.setText("Generar Nómina");
        menProcesos.add(generarnomina);

        reversarnomina.setText("Reversar Nómina");
        menProcesos.add(reversarnomina);

        jMenuBar1.add(menProcesos);

        consulta.setText("Consultas");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        Departamentos.setText("Departamentos");
        Departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentosActionPerformed(evt);
            }
        });
        consulta.add(Departamentos);

        jMenuItem1.setText("Puestos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        consulta.add(jMenuItem1);

        Empleados.setText("Empleados");
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });
        consulta.add(Empleados);

        EmpDepart.setText("Empleados por Departamento");
        consulta.add(EmpDepart);

        EmpPuestos.setText("Empleados por Puestos");
        consulta.add(EmpPuestos);

        EmpFecha.setText("Empleados por Fecha de Ingreso");
        consulta.add(EmpFecha);

        NominaFecha.setText("Nómina por Fecha");
        consulta.add(NominaFecha);

        NominaIDEmp.setText("Nómona por ID_Empleado");
        consulta.add(NominaIDEmp);

        jMenuBar1.add(consulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUsuarioActionPerformed
        Usuarios us = new Usuarios();
        us.setVisible(true);
    }//GEN-LAST:event_itmUsuarioActionPerformed

    private void itmEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEmpleadoActionPerformed
        Empleados emp = new Empleados();
        emp.setVisible(true);
    }//GEN-LAST:event_itmEmpleadoActionPerformed

    private void itmDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDepartActionPerformed
        Departamento dep = new Departamento();
        dep.setVisible(true);
    }//GEN-LAST:event_itmDepartActionPerformed

    private void itmPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPuestoActionPerformed
        Puestos pu = new Puestos();
        pu.setVisible(true);
    }//GEN-LAST:event_itmPuestoActionPerformed

    private void DepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentosActionPerformed
        ConsultaDepart cdp = new ConsultaDepart();
        cdp.setVisible(true);
    }//GEN-LAST:event_DepartamentosActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        ConsultaPuestos cp = new ConsultaPuestos();
        cp.setVisible(true);
    }//GEN-LAST:event_consultaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ConsultaPuestos cp = new ConsultaPuestos();
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed
        ConsultaEmp cemp = new ConsultaEmp();
        cemp.setVisible(true);
    }//GEN-LAST:event_EmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Departamentos;
    private javax.swing.JMenuItem EmpDepart;
    private javax.swing.JMenuItem EmpFecha;
    private javax.swing.JMenuItem EmpPuestos;
    private javax.swing.JMenuItem Empleados;
    private javax.swing.JMenuItem NominaFecha;
    private javax.swing.JMenuItem NominaIDEmp;
    private javax.swing.JMenu consulta;
    private javax.swing.JMenuItem generarnomina;
    private javax.swing.JMenuItem itmDepart;
    private javax.swing.JMenuItem itmEmpleado;
    private javax.swing.JMenuItem itmPuesto;
    private javax.swing.JMenuItem itmUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblLetrero;
    public javax.swing.JMenu menMantenimientos;
    public javax.swing.JMenu menProcesos;
    private javax.swing.JMenuItem reversarnomina;
    // End of variables declaration//GEN-END:variables
}
